### ISSUE TITLE
Question in weight network

### ISSUE THREAD

**Issue by LichAmnesia** [hhromic/python-oslom-runner#1]
It seems like the oslom tool can not run now. And it seems like it can just use network that have weight. And can not apply to unweighted network.

**Comment by hhromic** [comment]
Hi,
I'm not sure what do you mean with "the oslom tool can not run now". Can you give a more specific description or error message?
Regarding weighted networks, you can simply assign a `weight=1` to all edges in your input and will behave like an unweighted network.

Cheers!
Hugo

**Comment by LichAmnesia** [comment]
I just want to use this for an unweighted network. 
In the original oslom it can cover this situation, but in your implementation I should add a new column for this situation. Maybe I can fix this and pull a new request for you?
