### ISSUE TITLE
oslom_dir.exe error

### ISSUE THREAD

**Issue by musman-ashraf** [hhromic/python-oslom-runner#3]
Hi,
I want to use your wrapper. I have downloaded oslom as well as installed oslom runner. After running OSLOM2->compile_all.sh I have got oslom_dir and oslom_undir files. However, while running either of these file I get  "**The procedure entry point _ZNKSt7__cxx1112basic_stringlcST11char_traitslcESalcEE7compareEPKc could not be located in the dynamic link library ..\OSLOM2\oslom_dir.exe.**"  Any fix is highly appreciated!

**Comment by hhromic** [comment]
Hi,
I noticed that you are building for Windows. I never built OSLOM in Windows before so I don't really have any tips or help to give, unfortunately. Perhaps you can contact the OSLOM maintainers to help you better with that? It is not really an issue with this wrapper.

Even if you succeed on building OSLOM for Windows, I also haven't tested the wrapper in Windows, so not sure if it will work either (maybe it does, but I have never confirmed). Nevertheless good luck.

As this is not an issue with the wrapper itself, I'm going to close this ticket. I'm sorry I can't help you any further at the moment. Thanks!

**Comment by hhromic** [comment]
If you manage to build OSLOM for Windows and there are issues with the wrapper after that, I encourage you to post that here anyway. Maybe there are minor things to fix here and I would happily help with that.
